-- ============================================================
--  حماية الدخول: قفل الحساب بعد محاولات فاشلة + سجل أحداث الدخول
--  شغّله بعد 05_accounting.sql
--
--  القفل هنا مرتبط باسم المستخدم داخل قاعدة البيانات، فيعمل حتى لو بدّل
--  المهاجم جهازه أو مسح بيانات المتصفح — بعكس القفل المحلي في auth.js
--  الذي هو طبقة أولى لتحسين التجربة فقط.
-- ============================================================

-- ------------------------------------------------------------
-- 1) أعمدة القفل على ملف المستخدم
-- ------------------------------------------------------------
alter table public.profiles
  add column if not exists failed_attempts integer not null default 0;

alter table public.profiles
  add column if not exists locked_until timestamptz;

-- ------------------------------------------------------------
-- 2) سجل أحداث الدخول (نجاح/فشل) — للمراجعة الأمنية
--    ip_hint: أثر مختصر للمصدر إن توفّر، وليس عنوانًا كاملًا
-- ------------------------------------------------------------
create table if not exists public.auth_events (
  id         bigint generated by default as identity primary key,
  event      text not null,
  username   text,
  user_id    uuid references public.profiles(id) on delete set null,
  ip_hint    text,
  created_at timestamptz not null default now()
);

create index if not exists idx_auth_events_at
  on public.auth_events (created_at desc);
create index if not exists idx_auth_events_user
  on public.auth_events (username, created_at desc);

-- ------------------------------------------------------------
-- 3) هل الحساب مقفول الآن؟
--    تُستدعى قبل محاولة الدخول، فلا بد أن تكون متاحة لغير المسجّلين (anon)
-- ------------------------------------------------------------
create or replace function public.is_locked(p_username text)
returns boolean
language sql
stable security definer
set search_path to 'public'
as $$
  select coalesce(
    (select locked_until is not null and locked_until > now()
       from public.profiles where username = p_username), false);
$$;

-- ------------------------------------------------------------
-- 4) تسجيل محاولة فاشلة — وقفل الحساب ٥ دقائق بعد ٥ محاولات
-- ------------------------------------------------------------
create or replace function public.register_failed_login(p_username text)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_id uuid;
begin
  select id into v_id from public.profiles where username = p_username;
  -- اسم مستخدم غير موجود: لا نفعل شيئًا ولا نكشف ذلك للمتصل
  if v_id is null then return; end if;

  update public.profiles
     set failed_attempts = failed_attempts + 1,
         locked_until = case
           when failed_attempts + 1 >= 5 then now() + interval '5 minutes'
           else locked_until
         end
   where id = v_id;

  insert into public.auth_events (event, username, user_id)
  values ('login_failed', p_username, v_id);
end $$;

-- ------------------------------------------------------------
-- 5) دخول ناجح: تصفير العدّاد وفكّ القفل
--    الدالة تفكّ قفل الحساب، فلا يجوز أن يفكّ أحدٌ قفل حساب غيره:
--    تُرفض أي محاولة لتمرير معرّف مستخدم آخر.
-- ------------------------------------------------------------
create or replace function public.clear_failed_logins(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if auth.uid() is null or p_user_id <> auth.uid() then
    raise exception 'غير مصرح' using errcode = '42501';
  end if;

  update public.profiles
     set failed_attempts = 0, locked_until = null
   where id = p_user_id;

  insert into public.auth_events (event, username, user_id)
  values ('login_success',
          (select username from public.profiles where id = p_user_id),
          p_user_id);
end $$;

-- ------------------------------------------------------------
-- 6) تسجيل حدث عام (خروج مثلًا)
-- ------------------------------------------------------------
create or replace function public.log_auth_event(p_event text, p_username text)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  insert into public.auth_events (event, username, user_id)
  values (p_event, p_username, auth.uid());
end $$;

-- ------------------------------------------------------------
-- 7) الصلاحيات
--    is_locked وregister_failed_login متاحتان لغير المسجّل، لأنهما
--    تُستدعيان قبل وجود جلسة. والباقي للمسجّلين فقط.
-- ------------------------------------------------------------
revoke all on function public.is_locked(text)              from public, anon, authenticated;
revoke all on function public.register_failed_login(text)  from public, anon, authenticated;
revoke all on function public.clear_failed_logins(uuid)    from public, anon, authenticated;
revoke all on function public.log_auth_event(text, text)   from public, anon, authenticated;

grant execute on function public.is_locked(text)             to anon, authenticated;
grant execute on function public.register_failed_login(text) to anon, authenticated;
grant execute on function public.clear_failed_logins(uuid)   to authenticated;
grant execute on function public.log_auth_event(text, text)  to authenticated;

-- ------------------------------------------------------------
-- 8) الحماية على سجل الأحداث
--    الكتابة تتم حصريًا من الدوال أعلاه (security definer)،
--    والقراءة للمدير فقط لأن السجل يكشف أسماء المستخدمين وأوقات دخولهم.
-- ------------------------------------------------------------
alter table public.auth_events enable row level security;

drop policy if exists p_auth_events_read on public.auth_events;
create policy p_auth_events_read on public.auth_events
  for select to authenticated
  using (public.my_role() = 'admin');

-- ------------------------------------------------------------
-- 9) صيانة: حذف الأحداث الأقدم من ٩٠ يومًا (شغّلها يدويًا وقت الحاجة)
-- ------------------------------------------------------------
-- delete from public.auth_events where created_at < now() - interval '90 days';
